spring:
  application:
    name: payment-api-service
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration


jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000  # 1 hour