spring:
  application:
    name: payment-api-service
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
idempotency:
  ttl: 24h
  ambiguous-failure-hold: 60s

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000  # 1 hour
